pr:
  branches:
    include:
      - dev
  paths:
    exclude:
      - docs/*
      - README.md

trigger:
  branches:
    include:
      - master

stages:
  - stage: Build_Stage
    displayName: Build Stage
    jobs:
      - job: WebApp
        displayName: Build Web App
        pool:
          name: Hosted Windows 2019 with VS2019 
          vmImage: 'windows-2019'
          demands: java
        variables:
          BuildConfiguration: release 
        
        steps:
        - task: DotNetCoreCLI@2
          inputs:
            command: 'restore'
            projects: '**/WebApp/WebApp.csproj'
        
        - task: DotNetCoreCLI@2
          inputs:
            command: 'build'
            projects: '**/WebApp/WebApp.csproj'
            arguments: '--configuration $(BuildConfiguration)'

        - task: DotNetCoreCLI@2
          displayName: Test
          inputs:
            command: test
            projects: '**/*UnitTest*.csproj'
            arguments: '--configuration $(BuildConfiguration)'
        
        - task: DotNetCoreCLI@2
          displayName: Publish
          inputs:
            command: publish
            publishWebProjects: True
            arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
            zipAfterPublish: True
        
        - task: PublishBuildArtifacts@1
          displayName: Publish Artifact (WebApp.zip)
          inputs:
            PathtoPublish: '$(build.artifactstagingdirectory)'
            ArtifactName: drop
            
        
        - task: AzureRmWebAppDeployment@4
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'Microsoft Azure #1(1)(25a98a18-5e94-4b21-9d17-e8cf45bfd81f)'
            appType: 'webAppLinux'
            WebAppName: 'cegid-demo'
            deployToSlotOrASE: true
            ResourceGroupName: 'cegid'
            SlotName: 'staging'
            packageForLinux: '$(build.artifactstagingdirectory)/**/WebApp.zip'